# Generated by Django 5.1.6 on 2025-03-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionitem',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
