# Generated by Django 5.1.6 on 2025-03-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submissionitem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
