# Generated by Django 5.1.6 on 2025-03-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_question_quiz_delete_choices_delete_question'),
        ('submission', '0003_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='quiz.quiz'),
        ),
    ]
