# Generated by Django 5.1.6 on 2025-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Trivia', 'Trivia'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('English', 'English'), ('World Languages', 'World Languages'), ('Art', 'Art'), ('Culture', 'Culture'), ('History', 'History')], max_length=255)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=255)),
            ],
        ),
    ]
